#!/bin/bash

# SAGA Project Initialization Script
# Creates the .saga directory structure and initial files
#
# Usage: init-project.sh [project-name] [--pm github|gitlab|none]

set -euo pipefail

# Defaults
PROJECT_NAME="${1:-}"
PM_PLATFORM="none"
DESCRIPTION=""

# Parse arguments
shift || true
while [[ $# -gt 0 ]]; do
  case $1 in
    --pm)
      PM_PLATFORM="${2:-none}"
      shift 2
      ;;
    --description)
      DESCRIPTION="${2:-}"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

# Validate
if [[ -z "$PROJECT_NAME" ]]; then
  echo "Usage: init-project.sh <project-name> [--pm github|gitlab|none] [--description \"...\"]"
  exit 1
fi

# Check if already initialized
if [[ -f ".saga/project.json" ]]; then
  echo "Error: SAGA project already initialized in this directory"
  echo "Delete .saga/ to reinitialize"
  exit 1
fi

echo "Initializing SAGA project: $PROJECT_NAME"

# Create directory structure
mkdir -p .saga/diagrams .saga/changes .saga/hooks .saga/knowledge

# Get timestamp
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Create project.json
cat > .saga/project.json << EOF
{
  "name": "$PROJECT_NAME",
  "description": "${DESCRIPTION:-$PROJECT_NAME}",
  "createdAt": "$TIMESTAMP",
  "pm": {
    "platform": "$PM_PLATFORM"
  },
  "settings": {
    "tddRequired": true,
    "autoPush": false,
    "executionMode": "sequential",
    "evaluatorEnabled": true,
    "allowReorder": true,
    "evaluateEveryNIterations": 3,
    "maxRetries": 3
  }
}
EOF

# Create SRS template
cat > .saga/srs.md << 'EOF'
# Software Requirements Specification

> Generated by SAGA - Run `/saga spec` to populate

## 1. Introduction

### 1.1 Purpose
<!-- Purpose of this document -->

### 1.2 Scope
<!-- Scope of the project -->

### 1.3 Definitions
<!-- Key terms and definitions -->

## 2. Overall Description

### 2.1 Product Perspective
<!-- How this product fits in the larger context -->

### 2.2 User Characteristics
<!-- Who will use this product -->

### 2.3 Constraints
<!-- Technical and business constraints -->

## 3. Functional Requirements

<!-- FR-001: Requirement description -->

## 4. Non-Functional Requirements

<!-- NFR-001: Requirement description -->

## 5. Acceptance Criteria

<!-- Acceptance criteria per requirement -->
EOF

# Create progress.txt
cat > .saga/progress.txt << 'EOF'
# SAGA Progress Log

## Codebase Patterns
<!-- Add reusable patterns discovered during development -->

---

EOF

# Create .gitignore
cat > .saga/.gitignore << 'EOF'
# SAGA runtime artifacts (should not be committed)
state.json
metrics.jsonl

# Keep these tracked:
# project.json
# srs.md
# plan.json
# trace.md
# progress.txt
# hooks/
# knowledge/
# diagrams/
# changes/
EOF

# Output summary
cat << EOF

SAGA Project Initialized

Project: $PROJECT_NAME
Description: ${DESCRIPTION:-$PROJECT_NAME}
PM Integration: $PM_PLATFORM

Files created:
  .saga/project.json    - Project configuration
  .saga/srs.md          - SRS template (run /saga spec to populate)
  .saga/progress.txt    - Progress tracking
  .saga/knowledge/      - Knowledge accumulation directory

Next steps:
  1. /saga init-hooks   - Set up lifecycle hooks (recommended)
  2. /saga spec         - Generate Software Requirements Specification
  3. /saga plan         - Create Epic/Feature/Story hierarchy
  4. /saga execute      - Start autonomous execution

EOF
